### ISSUE TITLE
imagemin-pngquant/index.js - Use of const in strict mode 

### ISSUE THREAD

**Issue by mkrishtopa** [gabrielcsapo/grunt-screenshot#22]
grunt
Loading "screenshot.js" tasks...ERROR
>> SyntaxError: /home/.../node_modules/imagemin-pngquant/index.js:2
>> const execBuffer = require('exec-buffer');
>> ^^^^^
>> Use of const in strict mode.

upd: here is the solution: https://www.webfoobar.com/index.php/comment/71#comment-71

**Comment by gabrielcsapo** [comment]
will look into this @mkrishtopa, what version of node / npm are you using?
